[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
CHROME_PATH = "/usr/bin/chromium"
